### ISSUE TITLE
소감

### ISSUE THREAD

**Issue by eunjijeon11** [eunjijeon11/review_classifier#1]
댓글에 소감을 작성해주세요

**Comment by eunjijeon11** [comment]
지금까지는 신문기사처럼 잘 정돈된 데이터만 사용했었는데, 에브리타임의 강의평을 사용하려니 전처리 과정이 생각보다 어려웠습니다. 더 좋은 성능의 자연어처리 모듈이 개발되면 좋을 것 같습니다!

**Comment by chaeyeon03** [comment]
이론적으로만 알고 있었던 나이브베이즈정리를 직접 프로그래밍으로 구현할 수 있어서 유익했다.  앞으로 파이썬을 더 배우며 다양한 모듈을 이용한 프로그램을 한 번 더 만들어보고 싶다.

**Comment by jeazure11** [comment]
한 번도 해보지 않았던 과정들이라 중간중간 고난을 겪기는 했지만 그 과정에서 우리가 컴사코에서 배웠던 것을 만나 매우 반가웠고, 새로운 모듈같이 잘 몰랐던 내용들을 새롭게 알아보고 사용하게 되어 매우 유익한 시간이었습니다. 또한 파이썬을 가지고 코딩하는 것을 보다 깊이 들어감으로써 더 배워서 더 잘 써보고 싶다는 생각이 많이 들었습니다.

**Comment by eunjijeon11** [comment]
끝!
